[project]
name = "key-balance-detection"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.10"
dependencies = [
    "requests>=2.32.3",
    "tabulate>=0.9.0",
    "wxpython>=4.2.2",
]
